version: '3.8'

services:
  aifusionbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-5000}
    image: ghcr.io/${GITHUB_REPOSITORY:-amul-thantharate/aifusionbot}:latest
    container_name: aifusionbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
      - PORT=${PORT:-5000}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M