remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: NovaChat-AI Documentation
description: Documentation for NovaChat-AI AI Assistant
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

# Navigation
nav:
  - title: Home
    url: /
  - title: Setup Guide
    url: /setup
  - title: Commands
    url: /commands
  - title: Changelog
    url: /changelog
  - title: API Guide
    url: /api
  - title: Development
    url: /development

# Footer
footer:
  copyright: " 2024 NovaChat-AI. All rights reserved."
