name: Dependency Review

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          deny-licenses: LGPL-2.0, GPL-3.0
          
      - name: Python Dependency Check
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip-audit -r requirements.txt --format json -o pip-audit-results.json
        continue-on-error: true

      - name: Upload dependency review results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-review-results
          path: pip-audit-results.json
