name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan on Sunday

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety pytest pytest-cov
          pip install -r requirements.txt

      - name: Run Bandit security scan
        run: |
          bandit -r ./app -f json -o bandit-results.json
        continue-on-error: true

      - name: Check dependencies for known vulnerabilities
        run: |
          safety check

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
